# Generated by Django 4.1.1 on 2023-06-21 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('socket', models.CharField(max_length=100)),
                ('cores', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('threads', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
