# Generated by Django 4.1.1 on 2023-06-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='form_factor',
            field=models.CharField(choices=[('E_ATX', 'E-ATX'), ('ATX', 'ATX'), ('MICRO_ATX', 'Micro-ATX'), ('MINI_ITX', 'Mini-ITX')], max_length=10),
        ),
    ]
