# Generated by Django 4.1.1 on 2023-07-12 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('air_cooler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.aircooler')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.case')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.cpu')),
                ('gpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.gpu')),
                ('hdd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.hdd')),
                ('liquid_cooler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.liquidcooler')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.motherboard')),
                ('psu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.psu')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.ram')),
                ('ssd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.ssd')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
