# Generated by Django 4.1.1 on 2023-07-30 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_build'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=10000)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.build')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
