# Generated by Django 4.1.1 on 2023-06-26 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_motherboard_form_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=10)),
                ('size', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('mhz', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('units', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
