# Generated by Django 4.1.1 on 2023-08-03 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='builds')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.build')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
