# Generated by Django 4.1.1 on 2023-06-26 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_gpuseries_gpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='eight_pin_connectors',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='six_pin_connectors',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
