# Generated by Django 4.1.1 on 2023-06-26 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_alter_gpu_eight_pin_connectors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.gpuseries'),
        ),
    ]
