# Generated by Django 4.1.1 on 2023-06-27 17:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_alter_chipset_id_alter_motherboardformfactor_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MotherboardFormFactor',
            new_name='PSUEfficiency',
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('watts', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('form_factor', models.CharField(choices=[('ATX', 'ATX'), ('TFX', 'TFX'), ('SFX', 'SFX')], max_length=10)),
                ('eight_pcie_connectors', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('six_pcie_connectors', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('efficiency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.psuefficiency')),
            ],
        ),
    ]
