# Generated by Django 4.1.1 on 2023-06-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_alter_gpu_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='chipset',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='socket',
            field=models.CharField(max_length=100),
        ),
    ]
