# Generated by Django 4.1.1 on 2023-06-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_rename_motherboardformfactor_psuefficiency_psu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psu',
            options={'ordering': ['id']},
        ),
    ]
