# Generated by Django 4.1.1 on 2023-06-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_hdd_ssd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdd',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
