# Generated by Django 4.1.1 on 2023-06-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_alter_hdd_name_alter_ssd_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpu',
            old_name='eight_pin_connectors',
            new_name='_8_pin_connectors',
        ),
    ]
