# Generated by Django 4.1.1 on 2023-06-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_rename_eight_pin_connectors_gpu__8_pin_connectors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpu',
            old_name='six_pin_connectors',
            new_name='_6_pin_connectors',
        ),
    ]
