# Generated by Django 4.1.1 on 2023-06-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_rename_six_pin_connectors_gpu__6_pin_connectors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psu',
            old_name='eight_pcie_connectors',
            new_name='_8_pcie_connectors',
        ),
    ]
