# Generated by Django 4.1.1 on 2023-06-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_rename_eight_pcie_connectors_psu__8_pcie_connectors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psu',
            old_name='six_pcie_connectors',
            new_name='_6_pcie_connectors',
        ),
    ]
