# Generated by Django 4.1.1 on 2023-06-28 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0015_rename_six_pcie_connectors_psu__6_pcie_connectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidCooler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('radiator', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('_80_mm_fans', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('_92_mm_fans', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('_120_mm_fans', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('_140_mm_fans', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('_200_mm_fans', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('supported_sockets', models.ManyToManyField(to='scraper.socket')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AirCooler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('supported_sockets', models.ManyToManyField(to='scraper.socket')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
