# Generated by Django 4.1.1 on 2023-06-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0016_liquidcooler_aircooler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircooler',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='liquidcooler',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
