# Generated by Django 4.1.1 on 2023-06-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0017_alter_aircooler_name_alter_liquidcooler_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aircooler',
            unique_together={('name', 'height')},
        ),
        migrations.AlterUniqueTogether(
            name='liquidcooler',
            unique_together={('name', 'radiator')},
        ),
    ]
