# Generated by Django 4.1.1 on 2023-07-03 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0018_alter_aircooler_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('motherboard_size', models.CharField(choices=[('E-ATX', 'E-ATX'), ('ATX', 'ATX'), ('Micro-ATX', 'Micro-ATX'), ('Mini-ITX', 'Mini-ITX')], max_length=10)),
                ('psu_size', models.CharField(choices=[('ATX', 'ATX'), ('TFX', 'TFX'), ('SFX', 'SFX')], max_length=10)),
                ('gpu_length', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('air_cooler_height', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('_120_radiator_support', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('_140_radiator_support', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('_240_radiator_support', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('_280_radiator_support', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('_360_radiator_support', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('_2_5_disk_slot', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('_3_5_disk_slot', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
